version: 0.2
phases:
  install:
    commands:
      - curl -sL "https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip" -o terraform.zip
      - unzip -q terraform.zip -d /usr/local/bin
      - terraform version
  pre_build:
    commands:
      - cd ${tf_working_dir}/${env}
      - terraform init -input=false
  build:
    commands:
      - terraform destroy -auto-approve -no-color -input=false
