version: 0.2
phases:
  install:
    commands:
      - curl -sL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o terraform.zip
      - unzip -q terraform.zip -d /usr/local/bin
      - terraform version
  pre_build:
    commands:
      - cd ${TF_WORKING_DIR}/${ENV}
      - terraform fmt -check -recursive
      - terraform init -input=false
      - terraform validate -no-color
  build:
    commands:
      - terraform apply -auto-approve -no-color -input=false
